# Generated by Django 5.1.15 on 2026-03-14 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_cpf_profile_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='marketing_consent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='marketing_consent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='signup_ip',
            field=models.CharField(blank=True, max_length=45),
        ),
    ]
