# Generated by Django 5.1.15 on 2026-03-13 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='accent_color',
        ),
        migrations.RemoveField(
            model_name='page',
            name='bg_color',
        ),
        migrations.AlterField(
            model_name='page',
            name='theme',
            field=models.CharField(choices=[('neon-dark', 'Neon Dark'), ('cyber-blue', 'Cyber Blue'), ('aurora', 'Aurora')], default='neon-dark', max_length=20),
        ),
    ]
