# Generated by Django 5.1.15 on 2026-03-14 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_remove_page_accent_color_remove_page_bg_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linkclick',
            name='referer',
            field=models.TextField(blank=True),
        ),
    ]
