# Generated by Django 5.1.15 on 2026-03-16 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_alter_linkclick_referer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='theme',
            field=models.CharField(choices=[('neon-dark', 'Neon Dark'), ('cyber-blue', 'Cyber Blue'), ('aurora', 'Aurora'), ('midnight-purple', 'Midnight Purple'), ('solar-flare', 'Solar Flare'), ('forest-dark', 'Forest Dark'), ('rose-gold', 'Rose Gold'), ('ocean-deep', 'Ocean Deep'), ('volcanic', 'Volcanic'), ('arctic', 'Arctic'), ('tokyo-night', 'Tokyo Night'), ('golden-hour', 'Golden Hour'), ('matrix', 'Matrix')], default='neon-dark', max_length=20),
        ),
    ]
