# Generated by Django 5.1.15 on 2026-03-16 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_add_pro_themes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='linkclick',
            name='user_agent',
        ),
        migrations.AddField(
            model_name='linkclick',
            name='device_type',
            field=models.CharField(choices=[('mobile', 'Mobile'), ('tablet', 'Tablet'), ('desktop', 'Desktop')], default='desktop', max_length=10),
        ),
    ]
