# Generated by Django 5.1.15 on 2026-03-14 01:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pages', '0003_alter_linkclick_referer'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('ip_anon', models.CharField(blank=True, max_length=45)),
                ('device_type', models.CharField(choices=[('mobile', 'Mobile'), ('tablet', 'Tablet'), ('desktop', 'Desktop')], default='desktop', max_length=10)),
                ('referer_domain', models.CharField(blank=True, max_length=200)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_views', to='pages.page')),
            ],
            options={
                'verbose_name': 'Visualização',
                'verbose_name_plural': 'Visualizações',
                'ordering': ['-viewed_at'],
            },
        ),
        migrations.CreateModel(
            name='DailyAggregate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('total_views', models.PositiveIntegerField(default=0)),
                ('total_clicks', models.PositiveIntegerField(default=0)),
                ('mobile_count', models.PositiveIntegerField(default=0)),
                ('desktop_count', models.PositiveIntegerField(default=0)),
                ('tablet_count', models.PositiveIntegerField(default=0)),
                ('top_referer', models.CharField(blank=True, max_length=200)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_aggregates', to='pages.page')),
            ],
            options={
                'verbose_name': 'Agregado Diário',
                'verbose_name_plural': 'Agregados Diários',
                'ordering': ['-date'],
                'unique_together': {('page', 'date')},
            },
        ),
    ]
